on:
  push:
  pull_request:

name: actions-cli

jobs:
  create-release:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master' && startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    needs: create-release
    if: always() && !failure() && !cancelled()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project # This would actually build your project, using zip for an example artifact build
        run: |
          zip --junk-paths my-artifact README.md
      - name: Upload Release Asset
        if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'master' && startsWith(github.ref, 'refs/tags/v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip